# Generated by Django 2.1.7 on 2019-02-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhisorgname', models.CharField(max_length=255)),
                ('dhisorguid', models.UUIDField()),
                ('dhisorgparent', models.CharField(max_length=255)),
                ('rproorgname', models.CharField(max_length=255)),
                ('rproorgid', models.UUIDField()),
                ('rproorgparent', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
