# Generated by Django 2.1.7 on 2019-02-28 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rapdhis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapping',
            name='dhisorguid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='sitemapping',
            name='rproorgid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
